[package]
name = "libmath"
version = "0.2.1"
authors = ["Janne K <0x022b@gmail.com>"]
license = "MIT"
repository = "https://github.com/scoobadog/libmath-rs"
description = "Mathematical utilities"
keywords = ["mean", "round", "rounding"]

[lib]
name = "math"

[dependencies]
rand = "0.3"
